//! Recipe-to-Rust code compiler.
//!
//! Generates Rust source code from ENDF recipe ASTs, producing specialized
//! parse functions that bypass the interpreter entirely. The generated code
//! calls the same `records.rs` primitives (read_cont, read_tab1, etc.) but
//! with statically known field assignments.

use std::collections::{HashMap, HashSet};
use std::fmt::Write as FmtWrite;

use super::ast::*;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Compile a set of (mf, mt, recipe) triples into a self-contained Rust source file.
///
/// The output contains one `parse_mfX_mtY` function per recipe plus a
/// `parse_section` dispatch function.
pub fn compile_catalogue(recipes: &[(i32, i32, &[RecipeNode])]) -> String {
    let mut code = generate_header();
    for &(mf, mt, recipe) in recipes {
        code.push_str(&compile_recipe(mf, mt, recipe));
        code.push('\n');
    }
    code.push_str(&generate_dispatch_fn(recipes));
    code
}

/// Compile a single recipe into a standalone parse function.
pub fn compile_recipe(mf: i32, mt: i32, recipe: &[RecipeNode]) -> String {
    let all_vars = collect_variables(recipe);
    let mut gen = CodeGen::new(mf, mt, all_vars);
    for node in recipe {
        gen.emit_node(node);
    }
    gen.finish()
}

// ---------------------------------------------------------------------------
// Header / dispatch generation
// ---------------------------------------------------------------------------

fn generate_header() -> String {
    r#"//! Auto-generated ENDF parse functions. DO NOT EDIT.
//!
//! Generated by the endf-parser recipe compiler.

#![allow(unused_variables, unused_mut, unused_assignments)]

use endf_parser::records::{self, read_cont, read_tab1, read_tab1_body, read_tab2, read_tab2_body, read_list, read_endf_numbers};
use endf_parser::fortran::{fortstr_to_f64, read_fort_int};
use endf_parser::value::{EndfKey, EndfValue, EndfTable};
use endf_parser::options::{ReadOpts, ParseOpts};
use endf_parser::error::{EndfError, EndfResult};

/// Convert an f64 to EndfValue, using Int when the value is an exact integer.
#[inline]
fn f64_to_endf_value(v: f64) -> EndfValue {
    if v.is_finite() && v == (v as i64) as f64 {
        EndfValue::Int(v as i64)
    } else {
        EndfValue::Float(v)
    }
}

/// Build an EndfValue list from a slice of i64.
#[inline]
fn list_from_i64(vals: &[i64]) -> EndfValue {
    EndfValue::List(vals.iter().map(|v| Some(EndfValue::Int(*v))).collect())
}

/// Build an EndfValue list from a slice of f64.
#[inline]
fn list_from_f64(vals: &[f64]) -> EndfValue {
    EndfValue::List(vals.iter().map(|v| Some(f64_to_endf_value(*v))).collect())
}

"#
    .to_string()
}

fn generate_dispatch_fn(recipes: &[(i32, i32, &[RecipeNode])]) -> String {
    let mut code = String::new();
    code.push_str(
        "/// Dispatch to the compiled parse function for the given MF/MT.\n\
         pub fn parse_section(\n    \
             mf: i32,\n    \
             mt: i32,\n    \
             lines: &[String],\n    \
             read_opts: &ReadOpts,\n    \
             parse_opts: &ParseOpts,\n\
         ) -> EndfResult<EndfValue> {\n    \
             match (mf, mt) {\n",
    );

    // Separate wildcard (mt == -1) from exact entries.
    let mut exact: Vec<(i32, i32)> = Vec::new();
    let mut wildcards: Vec<i32> = Vec::new();
    for &(mf, mt, _) in recipes {
        if mt == -1 {
            wildcards.push(mf);
        } else {
            exact.push((mf, mt));
        }
    }

    for (mf, mt) in &exact {
        let _ = writeln!(
            code,
            "        ({}, {}) => parse_mf{}_mt{}(lines, read_opts, parse_opts),",
            mf, mt, mf, mt
        );
    }
    for mf in &wildcards {
        let _ = writeln!(
            code,
            "        ({}, _) => parse_mf{}_wildcard(lines, read_opts, parse_opts),",
            mf, mf
        );
    }

    code.push_str(
        "        _ => Err(EndfError::RecipeParse {\n            \
             message: format!(\"no compiled parser for MF{}/MT{}\", mf, mt),\n        \
         }),\n    \
         }\n\
         }\n",
    );
    code
}

// ---------------------------------------------------------------------------
// Variable collection – pre-pass to find all variable names in a recipe
// ---------------------------------------------------------------------------

/// Recursively walk the recipe AST and collect all variable names that appear
/// anywhere (fields, conditions, loop bounds, abbreviations, etc.).
/// Returns a set of lowercased variable names (matching the `var_xxx` naming).
fn collect_variables(recipe: &[RecipeNode]) -> HashSet<String> {
    let mut vars = HashSet::new();
    for node in recipe {
        collect_vars_node(node, &mut vars);
    }
    vars
}

fn collect_vars_node(node: &RecipeNode, vars: &mut HashSet<String>) {
    match node {
        RecipeNode::HeadOrCont { fields, .. } => {
            for f in fields {
                collect_vars_expr(f, vars);
            }
        }
        RecipeNode::Tab1 { fields, x_var, y_var, table_name, .. } => {
            for f in fields {
                collect_vars_expr(f, vars);
            }
            collect_vars_extvar(x_var, vars);
            collect_vars_extvar(y_var, vars);
            if let Some(tn) = table_name {
                collect_vars_extvar(tn, vars);
            }
        }
        RecipeNode::Tab2 { fields, z_var, table_name, .. } => {
            for f in fields {
                collect_vars_expr(f, vars);
            }
            collect_vars_extvar(z_var, vars);
            if let Some(tn) = table_name {
                collect_vars_extvar(tn, vars);
            }
        }
        RecipeNode::List { fields, body, list_name, .. } => {
            for f in fields {
                collect_vars_expr(f, vars);
            }
            collect_vars_list_body(body, vars);
            if let Some(ln) = list_name {
                collect_vars_extvar(ln, vars);
            }
        }
        RecipeNode::Dir { fields, .. } => {
            for f in fields {
                collect_vars_expr(f, vars);
            }
        }
        RecipeNode::Intg { fields, ndigit, .. } => {
            for f in fields {
                collect_vars_expr(f, vars);
            }
            collect_vars_expr(ndigit, vars);
        }
        RecipeNode::Text { placeholders, .. } => {
            for ph in placeholders {
                if let Some(ref v) = ph.var {
                    collect_vars_extvar(v, vars);
                }
            }
        }
        RecipeNode::ForLoop { var, start, stop, body } => {
            vars.insert(var.to_lowercase());
            collect_vars_expr(start, vars);
            collect_vars_expr(stop, vars);
            for n in body {
                collect_vars_node(n, vars);
            }
        }
        RecipeNode::RepeatLoop { var, body, until } => {
            if let Some((v, init)) = var {
                vars.insert(v.to_lowercase());
                collect_vars_expr(init, vars);
            }
            for n in body {
                collect_vars_node(n, vars);
            }
            collect_vars_bool(until, vars);
        }
        RecipeNode::IfClause { branches, else_body } => {
            for b in branches {
                collect_vars_bool(&b.condition, vars);
                if let Some(ref la) = b.lookahead {
                    collect_vars_expr(la, vars);
                }
                for n in &b.body {
                    collect_vars_node(n, vars);
                }
            }
            if let Some(eb) = else_body {
                for n in eb {
                    collect_vars_node(n, vars);
                }
            }
        }
        RecipeNode::Section { name, body } => {
            collect_vars_extvar(name, vars);
            for n in body {
                collect_vars_node(n, vars);
            }
        }
        RecipeNode::Abbreviation { name: _, expr } => {
            // Don't insert the abbreviation name itself — it's a compile-time
            // substitution, not a runtime variable. We still collect variables
            // from the RHS expression in case they appear nowhere else.
            collect_vars_expr(expr, vars);
        }
        RecipeNode::Send | RecipeNode::Stop { .. } | RecipeNode::Comment(_) => {}
    }
}

fn collect_vars_expr(expr: &Expr, vars: &mut HashSet<String>) {
    match expr {
        Expr::Variable(v) | Expr::InconsistentVar(v) => {
            collect_vars_extvar(v, vars);
        }
        Expr::Neg(a) | Expr::Bracket(a) => collect_vars_expr(a, vars),
        Expr::Add(a, b) | Expr::Sub(a, b) | Expr::Mul(a, b)
        | Expr::Div(a, b) | Expr::Mod(a, b) => {
            collect_vars_expr(a, vars);
            collect_vars_expr(b, vars);
        }
        Expr::Number(_) | Expr::DesiredNumber(_) => {}
    }
}

fn collect_vars_extvar(v: &ExtVarName, vars: &mut HashSet<String>) {
    vars.insert(v.name.to_lowercase());
    for idx in &v.indices {
        collect_vars_expr(idx, vars);
    }
}

fn collect_vars_bool(expr: &BoolExpr, vars: &mut HashSet<String>) {
    match expr {
        BoolExpr::Comparison { left, right, .. } => {
            collect_vars_expr(left, vars);
            collect_vars_expr(right, vars);
        }
        BoolExpr::And(a, b) | BoolExpr::Or(a, b) => {
            collect_vars_bool(a, vars);
            collect_vars_bool(b, vars);
        }
    }
}

fn collect_vars_list_body(items: &[ListItem], vars: &mut HashSet<String>) {
    for item in items {
        match item {
            ListItem::Value(expr) => collect_vars_expr(expr, vars),
            ListItem::Loop { body, var, start, stop } => {
                vars.insert(var.to_lowercase());
                collect_vars_expr(start, vars);
                collect_vars_expr(stop, vars);
                collect_vars_list_body(body, vars);
            }
            ListItem::Padding => {}
        }
    }
}

// ---------------------------------------------------------------------------
// Code generator
// ---------------------------------------------------------------------------

struct CodeGen {
    code: String,
    indent: usize,
    mf: i32,
    mt: i32,
    /// All variables pre-collected from the recipe AST, to be declared at function scope.
    all_vars: HashSet<String>,
    /// Stack of active loop variable names.
    loop_vars: Vec<String>,
    /// Compile-time abbreviation table: name -> defining Expr.
    /// Scoped stack matching section nesting. When `expr_to_rust` encounters
    /// a scalar variable in this table, it substitutes the full expression inline.
    abbreviations: Vec<HashMap<String, Expr>>,
}

impl CodeGen {
    fn new(mf: i32, mt: i32, all_vars: HashSet<String>) -> Self {
        Self {
            code: String::with_capacity(4096),
            indent: 1,
            mf,
            mt,
            all_vars,
            loop_vars: Vec::new(),
            abbreviations: vec![HashMap::new()],
        }
    }

    /// Finish and return the complete function source.
    fn finish(self) -> String {
        let fn_name = if self.mt == -1 {
            format!("parse_mf{}_wildcard", self.mf)
        } else {
            format!("parse_mf{}_mt{}", self.mf, self.mt)
        };

        let mut out = String::with_capacity(self.code.len() + 256);
        let _ = writeln!(out, "pub fn {}(", fn_name);
        out.push_str("    lines: &[String],\n");
        out.push_str("    read_opts: &ReadOpts,\n");
        out.push_str("    parse_opts: &ParseOpts,\n");
        out.push_str(") -> EndfResult<EndfValue> {\n");
        out.push_str("    let mut ofs: usize = 0;\n");
        out.push_str("    let mut result = EndfValue::new_dict();\n");
        // Store MAT/MF/MT from first line
        out.push_str("    if !lines.is_empty() {\n");
        out.push_str("        let ctrl = records::read_ctrl(&lines[0], read_opts)?;\n");
        out.push_str(
            "        result.insert(\"MAT\", EndfValue::Int(ctrl.mat as i64));\n",
        );
        out.push_str(
            "        result.insert(\"MF\", EndfValue::Int(ctrl.mf as i64));\n",
        );
        out.push_str(
            "        result.insert(\"MT\", EndfValue::Int(ctrl.mt as i64));\n",
        );
        out.push_str("    }\n");

        // Pre-declare all variables at function scope so they are accessible
        // from any branch or nested block.
        let mut sorted_vars: Vec<&String> = self.all_vars.iter().collect();
        sorted_vars.sort();
        for var in &sorted_vars {
            let vn = format!("var_{}", var);
            // Use f64 as default; variables used as i64 will be cast when needed.
            // We use f64 because ENDF values can be float or int and f64 covers both.
            let _ = writeln!(out, "    let mut {}: f64 = 0.0;", vn);
        }
        if !sorted_vars.is_empty() {
            out.push('\n');
        }

        out.push_str(&self.code);
        out.push_str("    Ok(result)\n");
        out.push_str("}\n");
        out
    }

    // -- Indentation helpers ------------------------------------------------

    fn indent_str(&self) -> String {
        "    ".repeat(self.indent)
    }

    fn line(&mut self, s: &str) {
        let _ = writeln!(self.code, "{}{}", self.indent_str(), s);
    }

    fn blank(&mut self) {
        self.code.push('\n');
    }

    // -- Variable helpers ---------------------------------------------------

    /// Return a Rust-safe local variable name for an ENDF variable.
    fn var_name(name: &str) -> String {
        format!("var_{}", name.to_lowercase())
    }

    /// Assign an f64 value to a pre-declared variable.
    fn declare_or_assign_f64(&mut self, endf_name: &str, rhs: &str) {
        let vn = Self::var_name(endf_name);
        self.line(&format!("{} = {};", vn, rhs));
    }

    /// Assign an i64 value to a pre-declared f64 variable (cast to f64).
    fn declare_or_assign_i64(&mut self, endf_name: &str, rhs: &str) {
        let vn = Self::var_name(endf_name);
        self.line(&format!("{} = {} as f64;", vn, rhs));
    }

    // -- Abbreviation helpers -----------------------------------------------

    /// Check if a variable name is an abbreviation in the current scope chain.
    fn is_abbreviation(&self, name: &str) -> bool {
        let lower = name.to_lowercase();
        self.abbreviations.iter().rev().any(|scope| scope.contains_key(&lower))
    }

    /// Recursively expand abbreviation references in an expression.
    /// Scalar variables that are in the abbreviation table get replaced
    /// with their defining expression. Indexed variables are left as-is.
    fn expand_abbreviations(&self, expr: &Expr) -> Expr {
        match expr {
            Expr::Variable(v) if v.indices.is_empty() => {
                let lower = v.name.to_lowercase();
                for scope in self.abbreviations.iter().rev() {
                    if let Some(abbrev_expr) = scope.get(&lower) {
                        return self.expand_abbreviations(abbrev_expr);
                    }
                }
                expr.clone()
            }
            Expr::InconsistentVar(v) if v.indices.is_empty() => {
                let lower = v.name.to_lowercase();
                for scope in self.abbreviations.iter().rev() {
                    if let Some(abbrev_expr) = scope.get(&lower) {
                        return self.expand_abbreviations(abbrev_expr);
                    }
                }
                expr.clone()
            }
            Expr::Variable(_) | Expr::InconsistentVar(_) => expr.clone(),
            Expr::Number(_) | Expr::DesiredNumber(_) => expr.clone(),
            Expr::Neg(a) => Expr::Neg(Box::new(self.expand_abbreviations(a))),
            Expr::Bracket(a) => Expr::Bracket(Box::new(self.expand_abbreviations(a))),
            Expr::Add(a, b) => Expr::Add(
                Box::new(self.expand_abbreviations(a)),
                Box::new(self.expand_abbreviations(b)),
            ),
            Expr::Sub(a, b) => Expr::Sub(
                Box::new(self.expand_abbreviations(a)),
                Box::new(self.expand_abbreviations(b)),
            ),
            Expr::Mul(a, b) => Expr::Mul(
                Box::new(self.expand_abbreviations(a)),
                Box::new(self.expand_abbreviations(b)),
            ),
            Expr::Div(a, b) => Expr::Div(
                Box::new(self.expand_abbreviations(a)),
                Box::new(self.expand_abbreviations(b)),
            ),
            Expr::Mod(a, b) => Expr::Mod(
                Box::new(self.expand_abbreviations(a)),
                Box::new(self.expand_abbreviations(b)),
            ),
        }
    }

    // -- Node dispatch ------------------------------------------------------

    fn emit_node(&mut self, node: &RecipeNode) {
        match node {
            RecipeNode::HeadOrCont {
                ctrl: _,
                fields,
                subtype: _,
            } => self.emit_head_or_cont(fields),

            RecipeNode::Tab1 {
                ctrl: _,
                fields,
                x_var,
                y_var,
                table_name,
            } => self.emit_tab1(fields, x_var, y_var, table_name),

            RecipeNode::Tab2 {
                ctrl: _,
                fields,
                z_var,
                table_name,
            } => self.emit_tab2(fields, z_var, table_name),

            RecipeNode::List {
                ctrl: _,
                fields,
                body,
                list_name,
            } => self.emit_list(fields, body, list_name),

            RecipeNode::ForLoop {
                var,
                start,
                stop,
                body,
            } => self.emit_for_loop(var, start, stop, body),

            RecipeNode::IfClause {
                branches,
                else_body,
            } => self.emit_if_clause(branches, else_body),

            RecipeNode::Section { name, body } => self.emit_section(name, body),

            RecipeNode::Abbreviation { name, expr } => self.emit_abbreviation(name, expr),

            RecipeNode::Send => {
                // No-op: section splitting already handled SEND records.
                self.line("// SEND");
            }

            RecipeNode::Text {
                ctrl: _,
                placeholders,
            } => self.emit_text(placeholders),

            RecipeNode::Dir { ctrl: _, fields } => self.emit_dir(fields),

            RecipeNode::Stop { message } => {
                let msg = message
                    .as_deref()
                    .unwrap_or("recipe stop");
                self.line(&format!(
                    "return Err(EndfError::Stop {{ message: \"{}\".to_string() }});",
                    msg
                ));
            }

            RecipeNode::Comment(_) => {
                // Skip comments
            }

            RecipeNode::Intg { .. } => {
                self.line("// TODO: INTG record not yet supported by compiler");
            }

            RecipeNode::RepeatLoop { .. } => {
                self.line("// TODO: RepeatLoop not yet supported by compiler");
            }
        }
    }

    // -- HeadOrCont ---------------------------------------------------------

    fn emit_head_or_cont(&mut self, fields: &[Expr; 6]) {
        self.line("// HEAD/CONT record");
        self.line("{");
        self.indent += 1;
        self.line("let (cont, _ctrl) = read_cont(lines.get(ofs).ok_or(EndfError::UnexpectedEndOfInput { line: ofs })?, read_opts)?;");
        self.line("ofs += 1;");

        let cont_fields = ["c1", "c2", "l1", "l2", "n1", "n2"];
        let is_int = [false, false, true, true, true, true];

        for (i, expr) in fields.iter().enumerate() {
            self.emit_cont_field_assignment(expr, cont_fields[i], is_int[i]);
        }

        self.indent -= 1;
        self.line("}");
    }

    fn emit_cont_field_assignment(&mut self, expr: &Expr, cont_field: &str, is_int: bool) {
        match expr {
            Expr::Number(n) => {
                // Constant validation: optionally check at runtime
                if *n == 0.0 {
                    self.line(&format!(
                        "// field {} expected 0 (validation skipped in compiled mode)",
                        cont_field
                    ));
                } else {
                    self.line(&format!(
                        "// field {} expected {} (validation skipped in compiled mode)",
                        cont_field, n
                    ));
                }
            }
            Expr::DesiredNumber(n) => {
                self.line(&format!(
                    "// field {} desired {} (validation skipped)",
                    cont_field, n
                ));
            }
            Expr::Variable(v) if v.indices.is_empty() => {
                if self.is_abbreviation(&v.name) {
                    // Abbreviation in field position: expanded expression is a
                    // known quantity — this is validation, not a variable read.
                    self.line(&format!(
                        "// field {} = abbreviation {} (validation skipped in compiled mode)",
                        cont_field, v.name
                    ));
                } else {
                    if is_int {
                        self.declare_or_assign_i64(&v.name, &format!("cont.{}", cont_field));
                        self.line(&format!(
                            "result.insert(\"{}\", EndfValue::Int({} as i64));",
                            v.name,
                            Self::var_name(&v.name)
                        ));
                    } else {
                        self.declare_or_assign_f64(&v.name, &format!("cont.{}", cont_field));
                        self.line(&format!(
                            "result.insert(\"{}\", f64_to_endf_value({}));",
                            v.name,
                            Self::var_name(&v.name)
                        ));
                    }
                }
            }
            Expr::InconsistentVar(v) if v.indices.is_empty() => {
                if self.is_abbreviation(&v.name) {
                    self.line(&format!(
                        "// field {} = abbreviation {} (validation skipped in compiled mode)",
                        cont_field, v.name
                    ));
                } else {
                    if is_int {
                        self.declare_or_assign_i64(&v.name, &format!("cont.{}", cont_field));
                        self.line(&format!(
                            "result.insert(\"{}\", EndfValue::Int({} as i64));",
                            v.name,
                            Self::var_name(&v.name)
                        ));
                    } else {
                        self.declare_or_assign_f64(&v.name, &format!("cont.{}", cont_field));
                        self.line(&format!(
                            "result.insert(\"{}\", f64_to_endf_value({}));",
                            v.name,
                            Self::var_name(&v.name)
                        ));
                    }
                }
            }
            Expr::Variable(v) => {
                // Indexed variable
                self.emit_indexed_var_store(v, cont_field, is_int, "result");
            }
            Expr::InconsistentVar(v) => {
                self.emit_indexed_var_store(v, cont_field, is_int, "result");
            }
            _ => {
                // Complex expression: emit a TODO comment
                // Complex expression (e.g. 6*NX where NX is an abbreviation).
                // After abbreviation expansion, this is computable from known
                // variables — treat as validation.
                self.line(&format!(
                    "// field {} complex expression (validation skipped in compiled mode)",
                    cont_field
                ));
            }
        }
    }

    fn emit_indexed_var_store(
        &mut self,
        v: &ExtVarName,
        cont_field: &str,
        is_int: bool,
        target: &str,
    ) {
        let val_expr = if is_int {
            format!("EndfValue::Int(cont.{} as i64)", cont_field)
        } else {
            format!("f64_to_endf_value(cont.{})", cont_field)
        };
        self.emit_nested_insert(target, &v.name, &v.indices, &val_expr);
    }

    /// Generate code to insert a value into a nested dict structure.
    /// For `name[i1, i2, ..., iN]`, this creates intermediate dicts as
    /// needed and inserts the value at the leaf:
    ///   target["name"][i1][i2]...[iN] = val_expr
    fn emit_nested_insert(
        &mut self,
        target: &str,
        name: &str,
        indices: &[Expr],
        val_expr: &str,
    ) {
        // Ensure the top-level container exists.
        self.line(&format!(
            "if !{}.contains_key(\"{}\") {{",
            target, name
        ));
        self.indent += 1;
        self.line(&format!(
            "{}.insert(\"{}\", EndfValue::new_dict());",
            target, name
        ));
        self.indent -= 1;
        self.line("}");

        if indices.is_empty() {
            // Scalar store (shouldn't happen here but handle gracefully)
            self.line(&format!(
                "{}.insert(\"{}\", {});",
                target, name, val_expr
            ));
            return;
        }

        // Build chain of get_mut/ensure-exists for all but the last index.
        // Use a local variable to navigate into the nested structure.
        let mut current = format!("{}.get_mut(\"{}\").unwrap()", target, name);
        for (depth, idx_expr) in indices[..indices.len() - 1].iter().enumerate() {
            let idx = self.expr_to_rust(idx_expr);
            let key_expr = format!("EndfKey::Int({} as i64)", idx);
            self.line(&format!(
                "if !{}.contains_key({}.clone()) {{",
                current, key_expr
            ));
            self.indent += 1;
            self.line(&format!(
                "{}.insert({}.clone(), EndfValue::new_dict());",
                current, key_expr
            ));
            self.indent -= 1;
            self.line("}");
            let nav_var = format!("_nav_{}", depth);
            self.line(&format!(
                "let {} = {}.get_mut({}).unwrap();",
                nav_var, current, key_expr
            ));
            current = nav_var;
        }

        // Insert value at the last index.
        let last_idx = self.expr_to_rust(indices.last().unwrap());
        self.line(&format!(
            "{}.insert(EndfKey::Int({} as i64), {});",
            current, last_idx, val_expr
        ));
    }

    /// Generate a Rust expression that reads an indexed variable from the
    /// result dict. Supports any number of indices via chained `.get()` calls.
    fn indexed_var_access(&self, name: &str, indices: &[Expr]) -> String {
        let mut expr = format!("result.get(\"{}\")", name);
        for idx in indices {
            let idx_rust = self.expr_to_rust(idx);
            expr = format!(
                "{}.and_then(|d| d.get(EndfKey::Int({} as i64)))",
                expr, idx_rust
            );
        }
        format!("{}.and_then(|v| v.as_float()).unwrap_or(0.0)", expr)
    }

    // -- TAB1 ---------------------------------------------------------------

    fn emit_tab1(
        &mut self,
        fields: &[Expr; 6],
        x_var: &ExtVarName,
        y_var: &ExtVarName,
        table_name: &Option<ExtVarName>,
    ) {
        self.line("// TAB1 record");
        self.line("{");
        self.indent += 1;

        self.line("let line_refs: Vec<&str> = lines[ofs..].iter().map(|s| s.as_str()).collect();");
        self.line(
            "let (cont, body, _ctrl, consumed) = read_tab1(&line_refs, 0, read_opts)?;",
        );
        self.line("ofs += consumed;");
        self.blank();

        // Map the first 4 header fields (C1, C2, L1, L2).
        // N1 (NR) and N2 (NP) are NOT mapped as named variables per interpreter behavior.
        let cont_fields = ["c1", "c2", "l1", "l2"];
        let is_int = [false, false, true, true];

        // Header fields go into the result dict directly (matching interpreter behavior).
        for (i, expr) in fields[..4].iter().enumerate() {
            self.emit_cont_field_assignment(expr, cont_fields[i], is_int[i]);
        }

        self.blank();

        // Store table data
        if let Some(ref tn) = table_name {
            self.line(&format!(
                "let mut tab_section = EndfValue::new_dict();",
            ));
            self.line("tab_section.insert(\"NBT\", list_from_i64(&body.nbt));");
            self.line("tab_section.insert(\"INT\", list_from_i64(&body.int));");
            self.line(&format!(
                "tab_section.insert(\"{}\", list_from_f64(&body.x));",
                x_var.name
            ));
            self.line(&format!(
                "tab_section.insert(\"{}\", list_from_f64(&body.y));",
                y_var.name
            ));
            self.line(&format!(
                "result.insert(\"{}\", tab_section);",
                tn.name
            ));
        } else {
            self.line("result.insert(\"NBT\", list_from_i64(&body.nbt));");
            self.line("result.insert(\"INT\", list_from_i64(&body.int));");
            self.line(&format!(
                "result.insert(\"{}\", list_from_f64(&body.x));",
                x_var.name
            ));
            self.line(&format!(
                "result.insert(\"{}\", list_from_f64(&body.y));",
                y_var.name
            ));
        }

        self.indent -= 1;
        self.line("}");
    }

    // -- TAB2 ---------------------------------------------------------------

    fn emit_tab2(
        &mut self,
        fields: &[Expr; 6],
        _z_var: &ExtVarName,
        table_name: &Option<ExtVarName>,
    ) {
        self.line("// TAB2 record");
        self.line("{");
        self.indent += 1;

        self.line("let line_refs: Vec<&str> = lines[ofs..].iter().map(|s| s.as_str()).collect();");
        self.line(
            "let (cont, body, _ctrl, consumed) = read_tab2(&line_refs, 0, read_opts)?;",
        );
        self.line("ofs += consumed;");
        self.blank();

        let cont_fields = ["c1", "c2", "l1", "l2"];
        let is_int = [false, false, true, true];

        for (i, expr) in fields[..4].iter().enumerate() {
            self.emit_cont_field_assignment(expr, cont_fields[i], is_int[i]);
        }

        self.blank();

        if let Some(ref tn) = table_name {
            self.line("let mut tab_section = EndfValue::new_dict();");
            self.line("tab_section.insert(\"NBT\", list_from_i64(&body.nbt));");
            self.line("tab_section.insert(\"INT\", list_from_i64(&body.int));");
            self.line(&format!(
                "result.insert(\"{}\", tab_section);",
                tn.name
            ));
        } else {
            self.line("result.insert(\"NBT\", list_from_i64(&body.nbt));");
            self.line("result.insert(\"INT\", list_from_i64(&body.int));");
        }

        self.indent -= 1;
        self.line("}");
    }

    // -- LIST ---------------------------------------------------------------

    fn emit_list(
        &mut self,
        fields: &[Expr; 6],
        body: &[ListItem],
        list_name: &Option<ExtVarName>,
    ) {
        self.line("// LIST record");
        self.line("{");
        self.indent += 1;

        self.line("let line_refs: Vec<&str> = lines[ofs..].iter().map(|s| s.as_str()).collect();");
        self.line(
            "let (cont, vals, _ctrl, consumed) = read_list(&line_refs, 0, read_opts)?;",
        );
        self.line("ofs += consumed;");
        self.blank();

        // Map header fields
        let cont_fields = ["c1", "c2", "l1", "l2", "n1", "n2"];
        let is_int = [false, false, true, true, true, true];

        for (i, expr) in fields.iter().enumerate() {
            self.emit_cont_field_assignment(expr, cont_fields[i], is_int[i]);
        }

        self.blank();

        let target = if list_name.is_some() {
            "list_section"
        } else {
            "result"
        };

        if list_name.is_some() {
            self.line("let mut list_section = EndfValue::new_dict();");
        }

        // Distribute list body values
        self.line("let mut vi: usize = 0;");
        self.emit_list_body_distribution(body, target);

        if let Some(ref ln) = list_name {
            self.line(&format!(
                "result.insert(\"{}\", list_section);",
                ln.name
            ));
        }

        self.indent -= 1;
        self.line("}");
    }

    fn emit_list_body_distribution(&mut self, body: &[ListItem], target: &str) {
        for item in body {
            match item {
                ListItem::Value(expr) => {
                    self.emit_list_value_store(expr, target);
                }
                ListItem::Loop {
                    body: loop_body,
                    var,
                    start,
                    stop,
                } => {
                    let start_s = self.expr_to_rust(start);
                    let stop_s = self.expr_to_rust(stop);
                    let loop_var = Self::var_name(var);
                    let loop_counter = format!("{}_loop_", loop_var);
                    self.line(&format!(
                        "for {} in ({} as i64)..=({} as i64) {{",
                        loop_counter, start_s, stop_s
                    ));
                    self.indent += 1;
                    self.line(&format!("{} = {} as f64;", loop_var, loop_counter));
                    self.emit_list_body_distribution(loop_body, target);
                    self.indent -= 1;
                    self.line("}");
                }
                ListItem::Padding => {
                    // Advance vi to next 6-element boundary
                    self.line("vi = (vi + 5) / 6 * 6;");
                }
            }
        }
    }

    fn emit_list_value_store(&mut self, expr: &Expr, target: &str) {
        // Helper: bounds-checked vals access
        let vals_get = "*vals.get(vi).ok_or(EndfError::UnexpectedEndOfInputMsg { message: format!(\"LIST body index {} out of bounds (len={})\", vi, vals.len()) })?";
        match expr {
            Expr::Variable(v) if v.indices.is_empty() => {
                if self.is_abbreviation(&v.name) {
                    // Abbreviation in list body: validation only, skip.
                    self.line("// list body abbreviation (validation skipped)");
                    self.line("vi += 1;");
                } else {
                    self.line(&format!(
                        "let _val = {};",
                        vals_get
                    ));
                    self.line(&format!(
                        "{}.insert(\"{}\", f64_to_endf_value(_val));",
                        target, v.name
                    ));
                    // Also set as local var for later use
                    self.declare_or_assign_f64(&v.name, "_val");
                    self.line("vi += 1;");
                }
            }
            Expr::Variable(v) => {
                // Indexed: e.g., ER[j] or F[k,kp]
                self.line(&format!(
                    "let _val = {};",
                    vals_get
                ));
                self.emit_nested_insert(target, &v.name, &v.indices, "f64_to_endf_value(_val)");
                self.line("vi += 1;");
            }
            Expr::Number(n) => {
                // Constant: validate or skip
                self.line(&format!(
                    "// list body constant {} (validation skipped)",
                    n
                ));
                self.line("vi += 1;");
            }
            Expr::InconsistentVar(v) if v.indices.is_empty() => {
                if self.is_abbreviation(&v.name) {
                    self.line("// list body abbreviation (validation skipped)");
                    self.line("vi += 1;");
                } else {
                    self.line(&format!(
                        "let _val = {};",
                        vals_get
                    ));
                    self.line(&format!(
                        "{}.insert(\"{}\", f64_to_endf_value(_val));",
                        target, v.name
                    ));
                    self.declare_or_assign_f64(&v.name, "_val");
                    self.line("vi += 1;");
                }
            }
            Expr::InconsistentVar(v) if !v.indices.is_empty() => {
                // Indexed inconsistent variable — same as Variable
                self.line(&format!(
                    "let _val = {};",
                    vals_get
                ));
                self.emit_nested_insert(target, &v.name, &v.indices, "f64_to_endf_value(_val)");
                self.line("vi += 1;");
            }
            _ => {
                // Complex expression (e.g., DesiredNumber) — validation only
                self.line("// list body expression (validation skipped)");
                self.line("vi += 1;");
            }
        }
    }

    // -- ForLoop ------------------------------------------------------------

    fn emit_for_loop(
        &mut self,
        var: &str,
        start: &Expr,
        stop: &Expr,
        body: &[RecipeNode],
    ) {
        let start_s = self.expr_to_rust(start);
        let stop_s = self.expr_to_rust(stop);
        let loop_var = Self::var_name(var);

        // Use a temporary loop counter to avoid conflicts with the pre-declared f64 variable.
        // The pre-declared var_xxx is updated inside the loop body for use by expressions.
        let loop_counter = format!("{}_loop_", loop_var);
        self.line(&format!(
            "for {} in ({} as i64)..=({} as i64) {{",
            loop_counter, start_s, stop_s
        ));
        self.indent += 1;
        self.line(&format!("{} = {} as f64;", loop_var, loop_counter));
        for node in body {
            self.emit_node(node);
        }
        self.indent -= 1;
        self.line("}");
    }

    // -- IfClause -----------------------------------------------------------

    fn emit_if_clause(
        &mut self,
        branches: &[IfBranch],
        else_body: &Option<Vec<RecipeNode>>,
    ) {
        // Pre-compute any lookahead conditions before the if-else chain.
        let mut lookahead_vars: Vec<Option<String>> = Vec::new();
        for (i, branch) in branches.iter().enumerate() {
            if branch.lookahead.is_some() {
                let var_name = format!("lookahead_ok_{}", i);
                self.line(&format!("let {} = {{", var_name));
                self.indent += 1;
                self.line("let saved_ofs = ofs;");
                self.line("let ok = (|| -> Result<bool, EndfError> {");
                self.indent += 1;
                self.line("if ofs >= lines.len() { return Ok(false); }");
                self.line("let (cont, _ctrl) = read_cont(&lines[ofs], read_opts)?;");
                let cond_rust = self.bool_expr_to_rust(&branch.condition);
                self.line(&format!("Ok({})", cond_rust));
                self.indent -= 1;
                self.line("})().unwrap_or(false);");
                // Note: ofs is not modified here (closure borrows immutably via lines[ofs])
                self.line("ok");
                self.indent -= 1;
                self.line("};");
                lookahead_vars.push(Some(var_name));
            } else {
                lookahead_vars.push(None);
            }
        }

        // Emit the if / else if / else chain.
        for (i, branch) in branches.iter().enumerate() {
            let cond = if let Some(ref lv) = lookahead_vars[i] {
                lv.clone()
            } else {
                self.bool_expr_to_rust(&branch.condition)
            };

            if i == 0 {
                self.line(&format!("if {} {{", cond));
            } else {
                self.line(&format!("}} else if {} {{", cond));
            }
            self.indent += 1;
            for node in &branch.body {
                self.emit_node(node);
            }
            self.indent -= 1;
        }

        if let Some(else_nodes) = else_body {
            self.line("} else {");
            self.indent += 1;
            for node in else_nodes {
                self.emit_node(node);
            }
            self.indent -= 1;
        }
        self.line("}");
    }

    // -- Section ------------------------------------------------------------

    fn emit_section(&mut self, name: &ExtVarName, body: &[RecipeNode]) {
        self.line(&format!("// Section: {}", name.name));
        self.line("{");
        self.indent += 1;
        // Push a new abbreviation scope for this section.
        self.abbreviations.push(HashMap::new());

        if name.indices.is_empty() {
            // Simple named section
            self.line(&format!(
                "let mut section_{} = EndfValue::new_dict();",
                name.name.to_lowercase()
            ));

            // Save the current target and redirect stores.
            // We use a swap-based approach: replace `result` with the section dict,
            // then swap back and insert.
            let section_var = format!("section_{}", name.name.to_lowercase());

            // We need to temporarily swap `result` so that stores go into the section.
            // However, since our generated code always stores into `result`, we use
            // a different approach: after the body, we'll manually fix up.
            // For now, emit body with a comment about the section.
            self.line(&format!(
                "// Stores in this block should go into section_{}",
                name.name.to_lowercase()
            ));
            self.line("// Using result-swap pattern");
            self.line(&format!(
                "std::mem::swap(&mut result, &mut {});",
                section_var
            ));

            for node in body {
                self.emit_node(node);
            }

            // Swap back
            self.line(&format!(
                "std::mem::swap(&mut result, &mut {});",
                section_var
            ));
            self.line(&format!(
                "result.insert(\"{}\", {});",
                name.name, section_var
            ));
        } else {
            // Indexed section: e.g., subsection[i]
            let section_var = format!("section_{}", name.name.to_lowercase());
            self.line(&format!("let mut {} = EndfValue::new_dict();", section_var));
            self.line(&format!(
                "std::mem::swap(&mut result, &mut {});",
                section_var
            ));

            for node in body {
                self.emit_node(node);
            }

            self.line(&format!(
                "std::mem::swap(&mut result, &mut {});",
                section_var
            ));

            // Insert with index key
            self.line(&format!(
                "if !result.contains_key(\"{}\") {{",
                name.name
            ));
            self.indent += 1;
            self.line(&format!(
                "result.insert(\"{}\", EndfValue::new_dict());",
                name.name
            ));
            self.indent -= 1;
            self.line("}");

            if name.indices.len() == 1 {
                let idx = self.expr_to_rust(&name.indices[0]);
                self.line(&format!(
                    "result.get_mut(\"{}\").unwrap().insert(EndfKey::Int({} as i64), {});",
                    name.name, idx, section_var
                ));
            } else {
                self.line(&format!(
                    "// TODO: multi-index section insert for {}",
                    name.name
                ));
            }
        }

        // Pop the abbreviation scope for this section.
        self.abbreviations.pop();
        self.indent -= 1;
        self.line("}");
    }

    // -- Abbreviation -------------------------------------------------------

    fn emit_abbreviation(&mut self, name: &str, expr: &Expr) {
        // No code generated — abbreviations are expanded at compile time.
        self.abbreviations.last_mut().unwrap()
            .insert(name.to_lowercase(), expr.clone());
    }

    // -- TEXT ---------------------------------------------------------------

    fn emit_text(&mut self, placeholders: &[TextPlaceholder]) {
        self.line("// TEXT record");
        self.line("{");
        self.indent += 1;
        self.line("let (text_rec, _ctrl) = records::read_text(lines.get(ofs).ok_or(EndfError::UnexpectedEndOfInput { line: ofs })?, read_opts)?;");
        self.line("ofs += 1;");

        if placeholders.len() == 1 {
            if let Some(ref v) = placeholders[0].var {
                self.line(&format!(
                    "result.insert(\"{}\", EndfValue::Str(text_rec.text.clone()));",
                    v.name
                ));
            }
        } else {
            // Multiple text fields: split by width
            let mut pos = 0;
            for ph in placeholders {
                let width = ph.width.unwrap_or(66);
                if let Some(ref v) = ph.var {
                    self.line(&format!(
                        "result.insert(\"{}\", EndfValue::Str(text_rec.text[{}..{}].to_string()));",
                        v.name, pos, pos + width
                    ));
                }
                pos += width;
            }
        }

        self.indent -= 1;
        self.line("}");
    }

    // -- DIR ----------------------------------------------------------------

    fn emit_dir(&mut self, fields: &[Expr; 4]) {
        self.line("// DIR record");
        self.line("{");
        self.indent += 1;
        self.line("let (dir_rec, _ctrl) = records::read_dir(lines.get(ofs).ok_or(EndfError::UnexpectedEndOfInput { line: ofs })?, read_opts)?;");
        self.line("ofs += 1;");

        let dir_fields = ["l1", "l2", "n1", "n2"];
        for (i, expr) in fields.iter().enumerate() {
            match expr {
                Expr::Variable(v) if v.indices.is_empty() => {
                    self.declare_or_assign_i64(&v.name, &format!("dir_rec.{}", dir_fields[i]));
                    self.line(&format!(
                        "result.insert(\"{}\", EndfValue::Int({} as i64));",
                        v.name,
                        Self::var_name(&v.name)
                    ));
                }
                Expr::Number(_) | Expr::DesiredNumber(_) => {
                    self.line(&format!(
                        "// DIR field {} constant (validation skipped)",
                        dir_fields[i]
                    ));
                }
                _ => {
                    self.line(&format!(
                        "// TODO: complex DIR field expression for {}",
                        dir_fields[i]
                    ));
                }
            }
        }

        self.indent -= 1;
        self.line("}");
    }

    // -- Expression rendering -----------------------------------------------

    /// Convert an AST expression to Rust source code.
    fn expr_to_rust(&self, expr: &Expr) -> String {
        match expr {
            Expr::Number(n) => {
                if *n == (*n as i64) as f64 {
                    format!("{}_f64", *n as i64)
                } else {
                    format!("{}_f64", n)
                }
            }
            Expr::DesiredNumber(n) => {
                if *n == (*n as i64) as f64 {
                    format!("{}_f64", *n as i64)
                } else {
                    format!("{}_f64", n)
                }
            }
            Expr::Variable(v) if v.indices.is_empty() => {
                // Check if this is an abbreviation — expand inline
                let lower = v.name.to_lowercase();
                for scope in self.abbreviations.iter().rev() {
                    if let Some(abbrev_expr) = scope.get(&lower) {
                        return format!("({})", self.expr_to_rust(abbrev_expr));
                    }
                }
                format!("{} as f64", Self::var_name(&v.name))
            }
            Expr::Variable(v) => {
                self.indexed_var_access(&v.name, &v.indices)
            }
            Expr::InconsistentVar(v) if v.indices.is_empty() => {
                let lower = v.name.to_lowercase();
                for scope in self.abbreviations.iter().rev() {
                    if let Some(abbrev_expr) = scope.get(&lower) {
                        return format!("({})", self.expr_to_rust(abbrev_expr));
                    }
                }
                format!("{} as f64", Self::var_name(&v.name))
            }
            Expr::InconsistentVar(v) => {
                self.indexed_var_access(&v.name, &v.indices)
            }
            Expr::Neg(inner) => {
                format!("-({})", self.expr_to_rust(inner))
            }
            Expr::Add(a, b) => {
                format!("({} + {})", self.expr_to_rust(a), self.expr_to_rust(b))
            }
            Expr::Sub(a, b) => {
                format!("({} - {})", self.expr_to_rust(a), self.expr_to_rust(b))
            }
            Expr::Mul(a, b) => {
                format!("({} * {})", self.expr_to_rust(a), self.expr_to_rust(b))
            }
            Expr::Div(a, b) => {
                format!("({} / {})", self.expr_to_rust(a), self.expr_to_rust(b))
            }
            Expr::Mod(a, b) => {
                format!("(({}) as i64 % ({}) as i64) as f64", self.expr_to_rust(a), self.expr_to_rust(b))
            }
            Expr::Bracket(inner) => {
                format!("({})", self.expr_to_rust(inner))
            }
        }
    }

    /// Convert a boolean expression to Rust source code.
    fn bool_expr_to_rust(&self, expr: &BoolExpr) -> String {
        match expr {
            BoolExpr::Comparison { left, op, right } => {
                let l = self.expr_to_rust(left);
                let r = self.expr_to_rust(right);
                let op_str = match op {
                    CmpOp::Eq => "==",
                    CmpOp::Ne => "!=",
                    CmpOp::Lt => "<",
                    CmpOp::Gt => ">",
                    CmpOp::Le => "<=",
                    CmpOp::Ge => ">=",
                };
                // Use integer comparison when comparing against integer literals
                let uses_int = matches!(right.as_ref(), Expr::Number(n) if *n == (*n as i64) as f64);
                if uses_int {
                    format!("({} as i64) {} ({} as i64)", l, op_str, r)
                } else {
                    format!("({}) {} ({})", l, op_str, r)
                }
            }
            BoolExpr::And(a, b) => {
                format!(
                    "({}) && ({})",
                    self.bool_expr_to_rust(a),
                    self.bool_expr_to_rust(b)
                )
            }
            BoolExpr::Or(a, b) => {
                format!(
                    "({}) || ({})",
                    self.bool_expr_to_rust(a),
                    self.bool_expr_to_rust(b)
                )
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::recipe::parse_recipe;

    #[test]
    fn test_compile_mf3_recipe() {
        let recipe_text = "\
[MAT, 3, MT/ ZA, AWR, 0, 0, 0, 0] HEAD
[MAT, 3, MT/ QM, QI, 0, LR, NR, NP / E / xs]TAB1 (xstable)
SEND
";
        let recipe = parse_recipe(recipe_text).unwrap();
        let code = compile_recipe(3, -1, &recipe);
        // Verify it contains key elements
        assert!(code.contains("read_cont"), "should call read_cont");
        assert!(code.contains("read_tab1"), "should call read_tab1");
        assert!(code.contains("xstable"), "should reference xstable section");
        assert!(code.contains("var_za"), "should have var_za");
        assert!(code.contains("var_awr"), "should have var_awr");
        assert!(code.contains("var_qm"), "should have var_qm");
        assert!(code.contains("var_qi"), "should have var_qi");
        assert!(code.contains("var_lr"), "should have var_lr");
    }

    #[test]
    fn test_compile_head_only() {
        let recipe_text = "[MAT, 3, MT/ ZA, AWR, 0, 0, 0, 0] HEAD\nSEND\n";
        let recipe = parse_recipe(recipe_text).unwrap();
        let code = compile_recipe(3, -1, &recipe);
        assert!(code.contains("let (cont, _ctrl) = read_cont"));
        assert!(code.contains("var_za = cont.c1;"));
        assert!(code.contains("var_awr = cont.c2;"));
    }

    #[test]
    fn test_compile_for_loop() {
        let recipe_text = "\
for i = 1 to NR:
[MAT, 3, MT/ C1, C2, L1, L2, N1, N2]CONT
endfor
";
        let recipe = parse_recipe(recipe_text).unwrap();
        let code = compile_recipe(3, -1, &recipe);
        assert!(code.contains("for var_i_loop_ in"));
        assert!(code.contains("var_nr"));
    }

    #[test]
    fn test_compile_if_clause() {
        let recipe_text = "\
if LFW == 0:
SEND
elif LFW == 1:
SEND
else:
SEND
endif
";
        let recipe = parse_recipe(recipe_text).unwrap();
        let code = compile_recipe(3, -1, &recipe);
        assert!(code.contains("if"));
        assert!(code.contains("else if"));
        assert!(code.contains("else"));
    }

    #[test]
    fn test_compile_section() {
        let recipe_text = "\
(mysection)
[MAT, 3, MT/ C1, C2, L1, L2, N1, N2]CONT
(/mysection)
";
        let recipe = parse_recipe(recipe_text).unwrap();
        let code = compile_recipe(3, -1, &recipe);
        assert!(code.contains("section_mysection"));
        assert!(code.contains("result.insert(\"mysection\""));
    }

    #[test]
    fn test_compile_abbreviation() {
        let recipe_text = "NW := 6*NRS + 1\n";
        let recipe = parse_recipe(recipe_text).unwrap();
        let code = compile_recipe(3, -1, &recipe);
        // Abbreviation should NOT generate a var_nw declaration or assignment.
        assert!(!code.contains("var_nw"), "abbreviation should not create a runtime variable");
        // The RHS variables should still be declared (they appear in collect_vars_expr).
        assert!(code.contains("var_nrs"), "RHS vars should still be declared");
    }

    #[test]
    fn test_compile_catalogue_dispatch() {
        let recipe_text = "[MAT, 3, MT/ ZA, AWR, 0, 0, 0, 0] HEAD\nSEND\n";
        let recipe = parse_recipe(recipe_text).unwrap();
        let code = compile_catalogue(&[(3, -1, &recipe)]);
        assert!(code.contains("pub fn parse_section("));
        assert!(code.contains("parse_mf3_wildcard"));
    }
}
